### ISSUE TITLE
Fix DataRange post processor

### ISSUE THREAD

**Issue by bilby91** [g8labs/noventius#61]
# Idea

The post processor is no working correctly and is disabled in the projects now. We are going to provide some sample reports that generate the issue.

**Comment by andres99x** [comment]
Ref: http://reports.unicorniomedia.com/reports/LinkOffersReport?utf8=✓&format=html&q%5Blink_offer_id%5D=9&q%5Butm_source%5D=&q%5Butm_medium%5D=&q%5Butm_referral_domain%5D=&q%5Bstart_time%5D=01%2F08%2F2016+00%3A00&q%5Bend_time%5D=06%2F08%2F2016+00%3A00&q%5Bgroup_by%5D=day
